name: NodeJS with Webpack

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build
      run: |
        npm install
        npx webpack
        ls -latr
    - name: Download a Build Artifact
      uses: actions/download-artifact@v7.0.0
      with:
        # Destination path. Supports basic tilde expansion. Defaults to $GITHUB_WORKSPACE
        path: ./dist
    - name: Update Plugin
      env:
        CORTEX_API_KEY: ${{ secrets.SONAR_TOKEN }}    
      run: |
        ls -latr ./dist
        # Read and safely encode file contents
        blob_content=$(<dist/ui.html)
        escaped_blob=$(printf '%s' "$blob_content" | jq -Rs .)
        
        # Use heredoc for JSON (no quotes around EOF)
        cat <<EOF > payload.json
        {
          "blob": $escaped_blob,
          "contexts": [
            {
              "type": "text",
              "entityFilter": "[Circular Reference]"
            }
          ],
          "description": "description",
          "iconTag": "text",
          "isDraft": true,
          "minimumRoleRequired": "text",
          "name": "text",
          "proxyTag": "text",
          "version": "text"
        }
        EOF

        curl -L \
          --request PUT \
          --url 'https://api.getcortexapp.com/api/v1/plugins/4016' \
          --header "Authorization: Bearer $CORTEX_API_KEY" \
          --header "Content-Type: application/json" \
          --data @payload.json" 
          
